# Generated by Django 4.2.2 on 2023-07-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('inProgress', 'In progress'), ('late', 'Late'), ('awaiting', 'Awaiting'), ('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
