# Generated by Django 4.2.2 on 2023-07-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('inProgress', 'In progress'), ('late', 'Late'), ('awaiting', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=15),
        ),
    ]
